export const collegeTeams = [
  "Alabama Crimson Tide",
  "Clemson Tigers",
  "Georgia Bulldogs",
  "Ohio State Buckeyes",
  "Oklahoma Sooners",
  "Notre Dame Fighting Irish",
  "Michigan Wolverines",
  "Penn State Nittany Lions",
  "Florida Gators",
  "Texas Longhorns",
  "LSU Tigers",
  "Oregon Ducks",
  "Wisconsin Badgers",
  "Miami Hurricanes",
  "USC Trojans",
  "Auburn Tigers",
  "Texas A&M Aggies",
  "Iowa Hawkeyes",
  "Michigan State Spartans",
  "Washington Huskies",
  "Oklahoma State Cowboys",
  "Florida State Seminoles",
  "Nebraska Cornhuskers",
  "Tennessee Volunteers",
  "UCLA Bruins",
  "Baylor Bears",
  "Ole Miss Rebels",
  "Virginia Tech Hokies",
  "TCU Horned Frogs",
  "Utah Utes",
  "Stanford Cardinal",
  "West Virginia Mountaineers",
  "Arkansas Razorbacks",
  "Kentucky Wildcats",
  "Arizona State Sun Devils",
  "Mississippi State Bulldogs",
  "North Carolina Tar Heels",
  "Pittsburgh Panthers",
  "Iowa State Cyclones",
  "South Carolina Gamecocks",
  "Louisville Cardinals",
  "Virginia Cavaliers",
  "California Golden Bears",
  "Minnesota Golden Gophers",
  "Purdue Boilermakers",
  "Northwestern Wildcats",
  "Kansas State Wildcats",
  "Boston College Eagles",
  "Maryland Terrapins",
  "Arizona Wildcats",
]
